DEV_ENVIRONMENT = {
    'aws_region': '<AWS_REGION_NAME_WHERE_THE_SERVICE_IS_HOSTED>',
    'user_pool_id': '<COGNITO_USER_POOL_ID_WHERE_THE_USER_ACCOUNT_EXISTS>',
    'client_id': '<CLIENT_ID_FOR_THIS_APP_CREATED_IN_THE_COGNITO_USER_POOL>',
    'identity_pool_id': '<COGNITO_IDENTITY_POOL_ID_WHERE_THE_USER_POOL_IS_CONFIGURED>',
    'bucket_name': '<AN_EXISTING_S3_BUCKET_ON_AWS>'

}

TEST_ENVIRONMENT = {
    'aws_region': '<AWS_REGION_NAME_WHERE_THE_SERVICE_IS_HOSTED>',
    'user_pool_id': '<COGNITO_USER_POOL_ID_WHERE_THE_USER_ACCOUNT_EXISTS>',
    'client_id': '<CLIENT_ID_FOR_THIS_APP_CREATED_IN_THE_COGNITO_USER_POOL>',
    'identity_pool_id': '<COGNITO_IDENTITY_POOL_ID_WHERE_THE_USER_POOL_IS_CONFIGURED>',
    'bucket_name': '<AN_EXISTING_S3_BUCKET_ON_AWS>'

}

PROD_ENVIRONMENT = {
    'aws_region': '<AWS_REGION_NAME_WHERE_THE_SERVICE_IS_HOSTED>',
    'user_pool_id': '<COGNITO_USER_POOL_ID_WHERE_THE_USER_ACCOUNT_EXISTS>',
    'client_id': '<CLIENT_ID_FOR_THIS_APP_CREATED_IN_THE_COGNITO_USER_POOL>',
    'identity_pool_id': '<COGNITO_IDENTITY_POOL_ID_WHERE_THE_USER_POOL_IS_CONFIGURED>',
    'bucket_name': '<AN_EXISTING_S3_BUCKET_ON_AWS>'
}
